apiVersion: v1
kind: Secret
metadata:
  name: lpmde-secrets
  namespace: lpmde-production
type: Opaque
stringData:
  database-url: "postgresql://lpmde_user:LPMDE45000@postgres-service:5432/lpmde_db?serverVersion=16&charset=utf8"
  postgres-password: "LPMDE45000"
  app-secret: "votre-secret-key-symfony-aleatoire-32-caracteres"

---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: lpmde-production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG
  # Pour générer : kubectl create secret docker-registry ghcr-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=VOTRE_USERNAME \
  #   --docker-password=VOTRE_GITHUB_TOKEN \
  #   --dry-run=client -o yaml
